### ISSUE TITLE
OGRE_PROFILING_PROVIDER=internal is broken and crashes with segfault

### ISSUE THREAD

**Issue by Slamy** [OGRECave/ogre-next#197]
#### System Information
- Ogre Version: current master state
- Operating System / Platform: Debian and Windows 10. Doesn't depend on OS
- RenderSystem: OpenGL
- GPU: RTX 2070 Super

#### Detailled description
Compiled with
`cmake -DOGRE_PROFILING_PROVIDER=internal ..`

Crashes on start.

#### Callstack
```
#0  Ogre::v1::OverlayProfileSessionListener::displayResults (this=0x555555e6f140, 
    instance=0x555556893f20, bIter=..., maxTimeMillisecs=@0x7fffffffd734: 35.8540001, 
    newGuiHeight=@0x7fffffffd72c: 1325, profileCount=@0x7fffffffd730: 100)
    at /home/andre/GIT/ogre-next/Components/Overlay/src/OgreOverlayProfileSessionListener.cpp:169
#1  0x00007ffff7fb1bf6 in Ogre::v1::OverlayProfileSessionListener::displayResults (this=0x555555e6f140, 
    instance=<optimized out>, bIter=..., maxTimeMillisecs=<optimized out>, newGuiHeight=<optimized out>, 
    profileCount=@0x7fffffffd730: 100)
    at /home/andre/GIT/ogre-next/Components/Overlay/src/OgreOverlayProfileSessionListener.cpp:252
#2  0x00007ffff7fb1bf6 in Ogre::v1::OverlayProfileSessionListener::displayResults (this=0x555555e6f140, 
    instance=<optimized out>, bIter=..., maxTimeMillisecs=<optimized out>, newGuiHeight=<optimized out>, 
    profileCount=@0x7fffffffd730: 100)
    at /home/andre/GIT/ogre-next/Components/Overlay/src/OgreOverlayProfileSessionListener.cpp:252
#3  0x00007ffff7fb1bf6 in Ogre::v1::OverlayProfileSessionListener::displayResults (this=0x555555e6f140, 
    instance=<optimized out>, bIter=..., maxTimeMillisecs=<optimized out>, newGuiHeight=<optimized out>, 
    profileCount=@0x7fffffffd730: 100)
    at /home/andre/GIT/ogre-next/Components/Overlay/src/OgreOverlayProfileSessionListener.cpp:252
#4  0x00007ffff7fb2053 in Ogre::v1::OverlayProfileSessionListener::displayResults (this=0x555555e6f140, 
    root=..., maxTotalFrameTime=<optimized out>)
    at /home/andre/GIT/ogre-next/Components/Overlay/src/OgreOverlayProfileSessionListener.cpp:144
#5  0x00007ffff7a322a1 in Ogre::Profiler::displayResults (this=0x555555aa54b0)
    at /home/andre/GIT/ogre-next/OgreMain/src/OgreProfiler.cpp:543
#6  0x00007ffff7a33ddf in Ogre::Profiler::endProfile (groupID=1, profileName=..., this=<optimized out>)
    at /home/andre/GIT/ogre-next/OgreMain/src/OgreProfiler.cpp:413
#7  0x00007ffff7b9912e in Ogre::CompositorPass::profilingEnd (this=this@entry=0x555556eb22d0)
    at /home/andre/GIT/ogre-next/OgreMain/src/Compositor/Pass/OgreCompositorPass.cpp:455
#8  0x00007ffff7ba4956 in Ogre::CompositorPassQuad::execute (this=0x555556eb22d0, 
    lodCamera=<optimized out>)
    at /home/andre/GIT/ogre-next/OgreMain/src/Compositor/Pass/PassQuad/OgreCompositorPassQuad.cpp:326
#9  0x00007ffff7b80475 in Ogre::CompositorNode::_update (this=this@entry=0x555556e6a920, 
    lodCamera=lodCamera@entry=0x0, sceneManager=0x555555f40a60)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/andre/GIT/ogre-next/OgreMain/src/Compositor/OgreCompositorNode.cpp:800
#10 0x00007ffff7b8f19d in Ogre::CompositorWorkspace::_update (this=0x5555561ed910, 
    bInsideAutoreleasePool=<optimized out>)
    at /home/andre/GIT/ogre-next/OgreMain/src/Compositor/OgreCompositorWorkspace.cpp:813
#11 0x00007ffff7d2dba7 in Ogre::CubemapProbe::_updateRender (this=this@entry=0x555556570a20)
    at /home/andre/GIT/ogre-next/Components/Hlms/Pbs/src/Cubemaps/OgreCubemapProbe.cpp:601
#12 0x00007ffff7d354d5 in Ogre::ParallaxCorrectedCubemapAuto::updateExpensiveCollectedDirtyProbes (
    this=this@entry=0x55555656fe80, iterationThreshold=iterationThreshold@entry=0)
    at /home/andre/GIT/ogre-next/Components/Hlms/Pbs/src/Cubemaps/OgreParallaxCorrectedCubemapAuto.cpp:411
#13 0x00007ffff7d363a3 in Ogre::ParallaxCorrectedCubemapAuto::updateAllDirtyProbes (this=0x55555656fe80)
    at /home/andre/GIT/ogre-next/Components/Hlms/Pbs/src/Cubemaps/OgreParallaxCorrectedCubemapAuto.cpp:488
#14 0x000055555556932a in Demo::LocalCubemapsGameState::createScene01 (this=0x5555555bf200)
    at /home/andre/GIT/ogre-next/Samples/2.0/ApiUsage/LocalCubemaps/LocalCubemapsGameState.cpp:298
#15 0x00005555555735d0 in Demo::MainEntryPoints::mainAppSingleThreaded (argc=-9176, argv=0x7fffffffdbc0)
    at /home/andre/GIT/ogre-next/Samples/2.0/Common/src/System/Desktop/MainLoopSingleThreaded.cpp:99
#16 0x000055555556546c in mainApp (argv=<optimized out>, argc=<optimized out>)
    at /home/andre/GIT/ogre-next/Samples/2.0/ApiUsage/LocalCubemaps/LocalCubemaps.cpp:24
#17 main (argc=<optimized out>, argv=<optimized out>)
    at /home/andre/GIT/ogre-next/Samples/2.0/Common/include/MainEntryPointHelper.h:40

```

**Comment by darksylinc** [comment]
Try remotery which is much more tested.

It appears the Overlays (internal profiler) are tryng to render to the cubemaps

**Comment by darksylinc** [comment]
To expand a bit: internal profiler is not getting much attention because Overlays are deprecated.
Although internal methods to profile (i.e. no dependencies) are desired, the way it displays the results are not

**Comment by Slamy** [comment]
remotery worked out of the box. Thank you.
Surely it would be advised to somehow indicate that internal is not working. I don't know how many will try to use it and will have some bad surprise and are wondering why it won't work.
Maybe with #error preprocessor? Or removing the Cmake configuration value so internal can't be selected?

I will leave this issue open but I'm letting you decide whether you want to close it as the reason to open it for me is gone.
I guess it will depend on whether you want to support the internal profiler in the future or not?

I mean, I get your argument. Remotery allows to pause and to investigate while the internal is probably a capture of the moment.
